### PR TITLE
Order stars by time earned

### PR DESCRIPTION
**Pull request by rawling**
This gives lines that increase as expected if solved out of order.
Tooltips now identify which star was solved.

Ref issue #3

### CODE REVIEW

**Comment by jeroenheijmans** [comment]
PS. On two tiny other notes:

- I try to avoid `var` and use const/let everywhere
- The `_` variable name is my convention to indicate "there is a parameter there, but unused at the moment", so if we start using it might give it a proper name

I don't mind tweaking those things before merging anything, or you could change them yourself. Either's fine. (But be ware my above comment: I'm not sure yet if the main thing is something I'd want to change...)

**Comment by rawling** [comment]
Have updated for `const` (I'm stuck supporting older verisons of JS in my day job!) and `data` in place of `_`.

My dislike of the sort by calendar order rather than achieved order is that, if you *do* go back and solve out of order, it changes the history of the graph - suddenly the data points for the later stars are all shifted up, and have a score (or star count) against them that doesn't actually reflect the state of the scoreboard for the timestamp they're marked with.

**Comment by jeroenheijmans** [comment]
Thx for the update. I'm afraid I'll let the PR sit until Nov 2020 when I'll go for a round of updates for the next (?) Advent of Code edition. Either way: much appreciate the PR!

**Comment by kindermoumoute** [comment]
up?

**Comment by jeroenheijmans** [comment]
Allright, I went with the PR as is Thx for the ping. Will be releasing a new extension version shortly with these changes too.

**Pull request merged**
