### PR TITLE
Sum up all the medals, not only the second ones

### PR DESCRIPTION
**Pull request by silyevsk**

### CODE REVIEW

**Comment by jeroenheijmans** [comment]
Thanks for the PR! However, the current situation is in fact inentional. On the colored medals for each day, the first star's visual is merely a "silver lining" for the _actual_ medal, given out for completing the entire day. I prefer to have it merely as a "nice touch" in the visuals, but otherwise not part of the podium table. Hope that makes sense?

**Comment by silyevsk** [comment]
It makes sense, although having a total of all gold/silver/bronze per start would be really nice as well - after all the first and the second stars of the day give equal points, so to me it would make more sense to give two medals per day and not one. Maybe there can be a mode switch between show/count medal per second star vs medal per any star?

Thanks for the reply, and thank you for the great extension! I discovered it just a few days ago, and now I enjoy advent-of-code even more :)

**Comment by jeroenheijmans** [comment]
Sorry I haven't gotten around to fixing it for this 2020 edition. I do appreciate the PR! But due to work and personal stuff I just haven't been able to make more time. I'll try to revisit it before the 2021 edition. Hope you understand!

**Comment by jeroenheijmans** [comment]
Thought about it some more this year.

You do make a valid point with the "stars give equal points", but then again the default points-leaderboard then already gives you the full podium for that.

I'm gonna stick with the equivalent of 800 meter in athletics, with the first 400m lap "podium" just an in-between-measurement.

A toggle between counting all medals or only per-day medals... I'm not fully against it, but it does add more complexity (for users to understand things) so I'm hesitant. If people find this PR or open similar issues I'll reconsider, but for the moment I'll leave it as is.

Thanks again for your suggestion though! Hope you're having a good 2021-puzzle-year so far too!

**Pull request closed without merging**
