### PR TITLE
Add toggle to show all players in medal overview table

### PR DESCRIPTION
**Pull request by leyanlo**
Would this be ok? Would love to be able to see everyone in this table :-)

### CODE REVIEW

**Comment by jeroenheijmans** [comment]
Hmm, having a tie breaker makes perfect sense.

Not sure about showing all the people by default. There's one pro (seeing everyone!) but several cons:

- On some boards not everyone participates each year (e.g. my company's private leaderboard), and those people will clutter the table
- On boards with 50+ish people, it will take up a _lot_ of real estate
- A _podium_ is in essence about getting medals at all

Also, #39 might give something that you are after with all people in a table?

I'll be happy to merge your PR later either way, but I might tweak the specifics if that makes sense?

**Comment by leyanlo** [comment]
Ah just updated again showing the default behavior by default and adding a toggle all button. #39 does look really good, so maybe this is unnecessary. I trust your judgement!

**Comment by jeroenheijmans** [comment]
Taking some time to do some updates this year, found your PR again @leyanlo so thanks once more! Looks really nice indeed, can see the value in this.

I'll append a few commits locally before merging to:

- move the button to toggle this from the "plugin generic buttons" towards the actual graph itself
- remove the local-score-sorting in the podium table (for local score sorting the other graphs are meant, I want the medal overview to always be sorted on medals (first))

Your feature should be coming to the browser somewhere this week!

**Comment by leyanlo** [comment]
Yay thanks!

**Pull request merged**
