### PR TITLE
Add delta leaderboard

### PR DESCRIPTION
**Pull request by gg-dt**
This adds a delta leaderboard below the Stats per day. The delta leaderboard ranks users first by the number of gold stars, second by the median of the delta times of each day. Useful for communities where the AOC start time is at a bad time of day ;-) 

image

### CODE REVIEW

**Comment by jeroenheijmans** [comment]
Nice! This does sound like an interesting feature indeed.

What was the motivation for choosing `Median Delta Time` for the measure? More in line with AoC's private leaderboard would be to give everyone a score for each day based on their delta time, what would you think?

**Comment by gg-dt** [comment]
You are right, giving a daily score would be more like AoC's leaderboard style. 
The motivation for doing this with the median delta was:
- Simple to implement
- Eliminate outliers, for example if one had to pause while doing the second part of the puzzle or if one puzzle was really hard for someone
But of course this is a biased ranking and I am open to suggestions 😅

**Comment by jeroenheijmans** [comment]
Cheers, thanks for the prompt reply!

I do like this idea and would like to build of your PR and complete this as a feature, but have a couple things I'd like to tweak and/or consider:

- What the location should be of this. Should it take up real estate immediately? Or should it perhaps share space with another table? If we insert it at the suggested place that's a tradeoff, as it pushes down _other_ visualizations which others might prefer. -- One weird idea might be to have a "cumulative delta-time score" in the stats-per-day table?
- I really would prefer to have a scoring system for delta time, where you earn points for each day where you have a good delta. This allows people to have "a bad day" delta-wise, but still overall come out on top. I'm afraid that _median_ as a measure will have a weird effect for many datasets.
- Code-wise I have a few remarks. Please do consider them notes-to-self, not a request per say for you to fix. I'm already happy you provided a PR for this! ❤️

I'm not entirely sure if I'd get to this in 2021 still, especially since releasing an extension for browsers is a hassle, and it's a busy month as is (which indeed does include puzzling in AoC myself :D). Hope you'll understand!

Thanks again for the PR! Not sure when, but I'll follow-up some time.

**Comment by jeroenheijmans** [comment]
I apologize @gg-dt: my intention truly was to look at this in November already, but life happened this fall, so no big updates to the repo or extensions this year I'm afraid. I do appreciate the submission though and hope to get to it after this AoC'22 at some point. Hope you understand!

**Comment by gg-dt** [comment]
No worries! Have a wonderful advent of code 😄

**Comment by jeroenheijmans** [comment]
Thanks again for this contribution! I'm gonna merge it in via #79 after I make some tweaks. I will (a) try to make it take the same real estate as the per-day table (they both focus on delta times), and (b) update it a bit to do something a bit extra on top of "median time".

Expect to see your features in the plugin for the next edition! Cheers again!

**Comment by jeroenheijmans** [comment]
Here's a sneak preview of what it'll look like when merged with the other table view.

For the dummy data in the repo:

image

Or anonymized variant of one of my more interesting leaderboards:

image

**Pull request merged**
